name = "AbsArrFallbackTrap"
uuid = "df276cbc-0f70-4538-9ccc-82f2aba363e2"
authors = ["KlausC <klausC@users.noreply.github.com> and contributors"]
version = "0.1.0"

[deps]
InteractiveUtils = "b77e0a4c-d291-57a0-90e8-8db25a27a240"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"

[compat]
julia = "1.7"
